### ISSUE TITLE
Configure Dependabot for Transitdata repositories

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitdata#230]
Currently Dependabot creates pull requests against `master` branch, but we are using `develop` as the main development branch against which the pull requests should be done.

See https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file

Maybe also enable automatic version updates for dependencies instead of just security updates?

**Comment by mjaakko** [comment]
Example config with just security updates:

```yaml
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    open-pull-requests-limit: 0
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    open-pull-requests-limit: 0
```
